### ISSUE TITLE
AUTUMN_LOCAL_STORAGE_PATH crash when file is accessed

### ISSUE THREAD

**Issue by shyim** [revoltchat/autumn#9]
Hey,

I tried to setup S3 but I get always S3Error without any helpful message. So I saw in code support for local files using `AUTUMN_LOCAL_STORAGE_PATH`. It seems like writing files working but not reading.

```
thread 'actix-rt:worker:2' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/pool.rs:85:33
stack backtrace:
   0:          0x1032140 - std::backtrace_rs::backtrace::libunwind::trace::h6292875aed2739db
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:          0x1032140 - std::backtrace_rs::backtrace::trace_unsynchronized::h8e4cae471de489bb
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x1032140 - std::sys_common::backtrace::_print_fmt::h9b5c8993cc054166
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys_common/backtrace.rs:67:5
   3:          0x1032140 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h025a584127ec484d
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys_common/backtrace.rs:46:22
   4:          0x107825c - core::fmt::write::hc12d0803d7cd91f9
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/fmt/mod.rs:1096:17
   5:          0x1029402 - std::io::Write::write_fmt::hf551e7bfd8a97193
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/io/mod.rs:1568:15
   6:          0x1034465 - std::sys_common::backtrace::_print::h06e7e2e14f5705f1
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys_common/backtrace.rs:49:5
   7:          0x1034465 - std::sys_common::backtrace::print::h0bc916dc7550b9e3
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys_common/backtrace.rs:36:9
   8:          0x1034465 - std::panicking::default_hook::{{closure}}::h5ad01a85289feef4
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:208:50
   9:          0x1033fc3 - std::panicking::default_hook::h08254923b362a124
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:225:9
  10:          0x1034c01 - std::panicking::rust_panic_with_hook::hf455788adcc6037d
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:591:17
  11:          0x1034747 - std::panicking::begin_panic_handler::{{closure}}::h77f62bd790d73507
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:497:13
  12:          0x10325dc - std::sys_common::backtrace::__rust_end_short_backtrace::h425b40ec298ee3a1
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys_common/backtrace.rs:141:18
  13:          0x10346a9 - rust_begin_unwind
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:493:5
  14:          0x1075961 - core::panicking::panic_fmt::h1a635ccd39b86574
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/panicking.rs:92:14
  15:          0x10756f3 - core::option::expect_failed::ha87475f95863321c
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/option.rs:1292:5
  16:           0x54e65f - tokio::runtime::blocking::pool::spawn_blocking::h948597f852164303
  17:           0x43b7aa - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h28a4e146992a07ba
  18:           0x44bacc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9086e5a8b0a1ea32
  19:           0x55885b - <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll::hf99f402f5e2ac2ad
  20:           0x582ee7 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::h00221b1dce674f00
  21:           0x4d5515 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h28fc1776b1efbcca
  22:           0x4d4cb9 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h6bd969c979888f5a
  23:           0xdc46c1 - <core::pin::Pin<P> as core::future::future::Future>::poll::he41b5249af7b482a
  24:           0x61442f - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h5be6bc862ca0dac2
  25:           0x43e2ad - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h42cc8f570f27bf98
  26:           0x58909d - <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll::hd05829a343667aba
  27:           0x5b9269 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::hb39b55966b679030
  28:           0x52b384 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::hd30b7a9c0dd75c84
  29:           0x4f67e1 - <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll::h52b597d7835251cc
  30:           0x44c46f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h984a60181ba545e6
  31:           0x46137a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0badf3bccd13ff6f
  32:           0x4ecfdc - tokio::runtime::task::raw::poll::ha440b3bbfc95d746
  33:           0xfc95c3 - std::thread::local::LocalKey<T>::with::hb9b119d47c737a68
  34:           0xfe2a07 - tokio::task::local::LocalSet::tick::h50d53f76f886c843
  35:           0xf5731a - tokio::macros::scoped_tls::ScopedKey<T>::set::h2b8525658211642e
  36:           0xf5d74b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5b091028af80f405
  37:           0xf59f72 - std::thread::local::LocalKey<T>::with::hfa0971c26e7ac9e5
  38:           0xf574e5 - tokio::macros::scoped_tls::ScopedKey<T>::set::h82ceec5494a6f0fb
  39:           0xf5d648 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hc3cac2796d9982f2
  40:           0xf445bf - tokio::runtime::context::enter::hed4c7f17f1bcdcb8
  41:           0xf59acf - std::sys_common::backtrace::__rust_begin_short_backtrace::hcfe22e4e5d1b5f66
  42:           0xf529c3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfbc3c3a33de52672
  43:          0x103ca7a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h04fa9632ed2971ec
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/alloc/src/boxed.rs:1548:9
  44:          0x103ca7a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h26f394c18ccce17c
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/alloc/src/boxed.rs:1548:9
  45:          0x103ca7a - std::sys::unix::thread::Thread::new::thread_start::h3dc2fd766800d863
                               at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/sys/unix/thread.rs:71:17
```

**Comment by insertish** [comment]
`S3Error` is spat out when buckets don't exist usually, there's a fix here: https://github.com/revoltchat/self-hosted/blob/master/docker-compose.yml#L49.

I'll try to reproduce the local file error.

**Comment by insertish** [comment]
Support for local file storage has being dropped.
